Print to stdout when there is an exception
NickvisionApps/Denaro pull request #763
Opened 2023-12-25 05:22 UTC by JoseBritto

This PR should add logs in missed places.

2023-12-25 05:25 UTC, JoseBritto commented
Now this is just to make debugging for #762 a tiny bit easier. Will go  through and complete the PR by tuesday :)

2023-12-25 05:26 UTC, nlogozzo commented
Might be best to Ctrl+Shift+F for `catch` and add and print the exception where needed...

2023-12-25 05:31 UTC, JoseBritto commented
> Might be best to Ctrl+Shift+F for catch and add and print the exception where needed...
Alright! Also probably better to use Console.Error. I forgot that earlier

2023-12-25 06:13 UTC, nlogozzo commented
Console.WriteLine is probably fine...stdput and stderr point to the same terminal unless the programmer usually redirects it to a separate file which we don't really in this case...

2023-12-26 06:00 UTC, JoseBritto commented
> Console.WriteLine is probably fine...stdput and stderr point to the same terminal unless the programmer usually redirects it to a separate file which we don't really in this case...

It is actually two different streams but most terminals won't differentiate by default. Its standard thing for most programs to print use the correct output stream. Also users can manually redirect errors as well to a file or whatever. Since Denaro isn't a command line app, it probably doesn't really matter. Since I'm gonna have to go through everything anyway, might as well fix the few logs already being printed out.

2023-12-26 06:02 UTC, JoseBritto commented
I'll complete this in the afternoon. Have been a bit busy

2023-12-26 22:38 UTC, JoseBritto commented
Added Console.Error.WriteLine to most catch blocks that made sense to me. I ignored the ones that executed sql queries and such.

2023-12-26 22:43 UTC, nlogozzo requested changes

2023-12-26 22:43 UTC, nlogozzo commented on NickvisionMoney.GNOME/Views/AccountView.cs
> +
Can you remove these extra white spaces?

2023-12-26 22:43 UTC, nlogozzo commented on NickvisionMoney.GNOME/Views/AccountView.cs
> +
Here too

2023-12-26 22:43 UTC, nlogozzo commented on NickvisionMoney.GNOME/Views/NewAccountDialog.cs
> +
Here too

2023-12-26 22:45 UTC, JoseBritto commented
Idk why rider keeps adding these in

2023-12-26 23:02 UTC, nlogozzo approved these changes
Thanks!

2023-12-26 23:02 UTC, merged

2024-01-05 01:50 UTC, nlogozzo commented
https://github.com/NickvisionApps/Denaro/releases/tag/2024.1.0